'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Nucleus Model Set Index API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * BIM 360 Indexing Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 1.2.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _IndexResource = require('./IndexResource');

var _IndexResource2 = _interopRequireDefault(_IndexResource);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The IndexQueryResources model module.
 * @module model/IndexQueryResources
 * @version 1.2.0
 */
var IndexQueryResources = function () {
  /**
   * Constructs a new <code>IndexQueryResources</code>.
   * A set of resources associated with an index query result
   * @alias module:model/IndexQueryResources
   * @param fields {module:model/IndexResource} 
   * @param results {module:model/IndexResource} 
   */
  function IndexQueryResources(fields, results) {
    _classCallCheck(this, IndexQueryResources);

    IndexQueryResources.initialize(this, fields, results);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(IndexQueryResources, null, [{
    key: 'initialize',
    value: function initialize(obj, fields, results) {
      obj['fields'] = fields;
      obj['results'] = results;
    }

    /**
     * Constructs a <code>IndexQueryResources</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IndexQueryResources} obj Optional instance to populate.
     * @return {module:model/IndexQueryResources} The populated <code>IndexQueryResources</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new IndexQueryResources();

        if (data.hasOwnProperty('fields')) {
          obj['fields'] = _IndexResource2.default.constructFromObject(data['fields']);
        }
        if (data.hasOwnProperty('results')) {
          obj['results'] = _IndexResource2.default.constructFromObject(data['results']);
        }
      }
      return obj;
    }
  }]);

  return IndexQueryResources;
}();

/**
 * @member {module:model/IndexResource} fields
 */


IndexQueryResources.prototype['fields'] = undefined;

/**
 * @member {module:model/IndexResource} results
 */
IndexQueryResources.prototype['results'] = undefined;

exports.default = IndexQueryResources;
//# sourceMappingURL=IndexQueryResources.js.map