'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Nucleus Model Set Index API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * BIM 360 Indexing Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 1.2.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The IndexManifestSeedFileDocument model module.
 * @module model/IndexManifestSeedFileDocument
 * @version 1.2.0
 */
var IndexManifestSeedFileDocument = function () {
  /**
   * Constructs a new <code>IndexManifestSeedFileDocument</code>.
   * @alias module:model/IndexManifestSeedFileDocument
   * @param id {Number} Document ID in index results
   * @param versionUrn {String} Document version URN
   * @param viewableId {String} Document derivative service viewable ID
   * @param viewableGuid {String} Document derivative service viewable guid
   */
  function IndexManifestSeedFileDocument(id, versionUrn, viewableId, viewableGuid) {
    _classCallCheck(this, IndexManifestSeedFileDocument);

    IndexManifestSeedFileDocument.initialize(this, id, versionUrn, viewableId, viewableGuid);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(IndexManifestSeedFileDocument, null, [{
    key: 'initialize',
    value: function initialize(obj, id, versionUrn, viewableId, viewableGuid) {
      obj['id'] = id;
      obj['versionUrn'] = versionUrn;
      obj['viewableId'] = viewableId;
      obj['viewableGuid'] = viewableGuid;
    }

    /**
     * Constructs a <code>IndexManifestSeedFileDocument</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IndexManifestSeedFileDocument} obj Optional instance to populate.
     * @return {module:model/IndexManifestSeedFileDocument} The populated <code>IndexManifestSeedFileDocument</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new IndexManifestSeedFileDocument();

        if (data.hasOwnProperty('id')) {
          obj['id'] = _ApiClient2.default.convertToType(data['id'], 'Number');
        }
        if (data.hasOwnProperty('versionUrn')) {
          obj['versionUrn'] = _ApiClient2.default.convertToType(data['versionUrn'], 'String');
        }
        if (data.hasOwnProperty('viewableId')) {
          obj['viewableId'] = _ApiClient2.default.convertToType(data['viewableId'], 'String');
        }
        if (data.hasOwnProperty('viewableGuid')) {
          obj['viewableGuid'] = _ApiClient2.default.convertToType(data['viewableGuid'], 'String');
        }
      }
      return obj;
    }
  }]);

  return IndexManifestSeedFileDocument;
}();

/**
 * Document ID in index results
 * @member {Number} id
 */


IndexManifestSeedFileDocument.prototype['id'] = undefined;

/**
 * Document version URN
 * @member {String} versionUrn
 */
IndexManifestSeedFileDocument.prototype['versionUrn'] = undefined;

/**
 * Document derivative service viewable ID
 * @member {String} viewableId
 */
IndexManifestSeedFileDocument.prototype['viewableId'] = undefined;

/**
 * Document derivative service viewable guid
 * @member {String} viewableGuid
 */
IndexManifestSeedFileDocument.prototype['viewableGuid'] = undefined;

exports.default = IndexManifestSeedFileDocument;
//# sourceMappingURL=IndexManifestSeedFileDocument.js.map