'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Nucleus Model Set Index API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * BIM 360 Indexing Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 1.2.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _IndexManifestSeedFileDatabase = require('./IndexManifestSeedFileDatabase');

var _IndexManifestSeedFileDatabase2 = _interopRequireDefault(_IndexManifestSeedFileDatabase);

var _IndexManifestSeedFileDocument = require('./IndexManifestSeedFileDocument');

var _IndexManifestSeedFileDocument2 = _interopRequireDefault(_IndexManifestSeedFileDocument);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The IndexManifestSeedFile model module.
 * @module model/IndexManifestSeedFile
 * @version 1.2.0
 */
var IndexManifestSeedFile = function () {
  /**
   * Constructs a new <code>IndexManifestSeedFile</code>.
   * @alias module:model/IndexManifestSeedFile
   * @param id {Number} Seed file manifest id
   * @param urn {String} Seed file version URN
   * @param key {String} The BASE64 encoded seed file version URN
   * @param databases {Array.<module:model/IndexManifestSeedFileDatabase>} 
   * @param documents {Array.<module:model/IndexManifestSeedFileDocument>} 
   */
  function IndexManifestSeedFile(id, urn, key, databases, documents) {
    _classCallCheck(this, IndexManifestSeedFile);

    IndexManifestSeedFile.initialize(this, id, urn, key, databases, documents);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(IndexManifestSeedFile, null, [{
    key: 'initialize',
    value: function initialize(obj, id, urn, key, databases, documents) {
      obj['id'] = id;
      obj['urn'] = urn;
      obj['key'] = key;
      obj['databases'] = databases;
      obj['documents'] = documents;
    }

    /**
     * Constructs a <code>IndexManifestSeedFile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IndexManifestSeedFile} obj Optional instance to populate.
     * @return {module:model/IndexManifestSeedFile} The populated <code>IndexManifestSeedFile</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new IndexManifestSeedFile();

        if (data.hasOwnProperty('id')) {
          obj['id'] = _ApiClient2.default.convertToType(data['id'], 'Number');
        }
        if (data.hasOwnProperty('urn')) {
          obj['urn'] = _ApiClient2.default.convertToType(data['urn'], 'String');
        }
        if (data.hasOwnProperty('key')) {
          obj['key'] = _ApiClient2.default.convertToType(data['key'], 'String');
        }
        if (data.hasOwnProperty('databases')) {
          obj['databases'] = _ApiClient2.default.convertToType(data['databases'], [_IndexManifestSeedFileDatabase2.default]);
        }
        if (data.hasOwnProperty('documents')) {
          obj['documents'] = _ApiClient2.default.convertToType(data['documents'], [_IndexManifestSeedFileDocument2.default]);
        }
      }
      return obj;
    }
  }]);

  return IndexManifestSeedFile;
}();

/**
 * Seed file manifest id
 * @member {Number} id
 */


IndexManifestSeedFile.prototype['id'] = undefined;

/**
 * Seed file version URN
 * @member {String} urn
 */
IndexManifestSeedFile.prototype['urn'] = undefined;

/**
 * The BASE64 encoded seed file version URN
 * @member {String} key
 */
IndexManifestSeedFile.prototype['key'] = undefined;

/**
 * @member {Array.<module:model/IndexManifestSeedFileDatabase>} databases
 */
IndexManifestSeedFile.prototype['databases'] = undefined;

/**
 * @member {Array.<module:model/IndexManifestSeedFileDocument>} documents
 */
IndexManifestSeedFile.prototype['documents'] = undefined;

exports.default = IndexManifestSeedFile;
//# sourceMappingURL=IndexManifestSeedFile.js.map