'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Nucleus Model Set Index API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * BIM 360 Indexing Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 1.2.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _CollectionPage = require('./CollectionPage');

var _CollectionPage2 = _interopRequireDefault(_CollectionPage);

var _IndexView = require('./IndexView');

var _IndexView2 = _interopRequireDefault(_IndexView);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The IndexViewCollection model module.
 * @module model/IndexViewCollection
 * @version 1.2.0
 */
var IndexViewCollection = function () {
  /**
   * Constructs a new <code>IndexViewCollection</code>.
   * A set of index views.
   * @alias module:model/IndexViewCollection
   * @param page {module:model/CollectionPage} 
   * @param views {Array.<module:model/IndexView>} List of index views
   */
  function IndexViewCollection(page, views) {
    _classCallCheck(this, IndexViewCollection);

    IndexViewCollection.initialize(this, page, views);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(IndexViewCollection, null, [{
    key: 'initialize',
    value: function initialize(obj, page, views) {
      obj['page'] = page;
      obj['views'] = views;
    }

    /**
     * Constructs a <code>IndexViewCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IndexViewCollection} obj Optional instance to populate.
     * @return {module:model/IndexViewCollection} The populated <code>IndexViewCollection</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new IndexViewCollection();

        if (data.hasOwnProperty('page')) {
          obj['page'] = _CollectionPage2.default.constructFromObject(data['page']);
        }
        if (data.hasOwnProperty('views')) {
          obj['views'] = _ApiClient2.default.convertToType(data['views'], [_IndexView2.default]);
        }
      }
      return obj;
    }
  }]);

  return IndexViewCollection;
}();

/**
 * @member {module:model/CollectionPage} page
 */


IndexViewCollection.prototype['page'] = undefined;

/**
 * List of index views
 * @member {Array.<module:model/IndexView>} views
 */
IndexViewCollection.prototype['views'] = undefined;

exports.default = IndexViewCollection;
//# sourceMappingURL=IndexViewCollection.js.map