'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Nucleus Model Set Index API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * BIM 360 Indexing Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 1.2.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _BasicError = require('./BasicError');

var _BasicError2 = _interopRequireDefault(_BasicError);

var _IndexQueryResources = require('./IndexQueryResources');

var _IndexQueryResources2 = _interopRequireDefault(_IndexQueryResources);

var _Job = require('./Job');

var _Job2 = _interopRequireDefault(_Job);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The IndexJob model module.
 * @module model/IndexJob
 * @version 1.2.0
 */
var IndexJob = function () {
  /**
   * Constructs a new <code>IndexJob</code>.
   * A job token representing a POST, PATCH, PUT or DELETE operation on a Model Set
   * @alias module:model/IndexJob
   * @param jobId {String} The Job ID
   * @param modelSetId {String} The Model Set ID associated with the Job
   * @param status {module:model/IndexJob.StatusEnum} The current Job status
   * @param job {module:model/Job} 
   */
  function IndexJob(jobId, modelSetId, status, job) {
    _classCallCheck(this, IndexJob);

    IndexJob.initialize(this, jobId, modelSetId, status, job);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(IndexJob, null, [{
    key: 'initialize',
    value: function initialize(obj, jobId, modelSetId, status, job) {
      obj['jobId'] = jobId;
      obj['modelSetId'] = modelSetId;
      obj['status'] = status;
      obj['job'] = job;
    }

    /**
     * Constructs a <code>IndexJob</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IndexJob} obj Optional instance to populate.
     * @return {module:model/IndexJob} The populated <code>IndexJob</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new IndexJob();

        if (data.hasOwnProperty('jobId')) {
          obj['jobId'] = _ApiClient2.default.convertToType(data['jobId'], 'String');
        }
        if (data.hasOwnProperty('modelSetId')) {
          obj['modelSetId'] = _ApiClient2.default.convertToType(data['modelSetId'], 'String');
        }
        if (data.hasOwnProperty('modelSetVersion')) {
          obj['modelSetVersion'] = _ApiClient2.default.convertToType(data['modelSetVersion'], 'Number');
        }
        if (data.hasOwnProperty('resources')) {
          obj['resources'] = _IndexQueryResources2.default.constructFromObject(data['resources']);
        }
        if (data.hasOwnProperty('status')) {
          obj['status'] = _ApiClient2.default.convertToType(data['status'], 'String');
        }
        if (data.hasOwnProperty('job')) {
          obj['job'] = _Job2.default.constructFromObject(data['job']);
        }
        if (data.hasOwnProperty('errors')) {
          obj['errors'] = _ApiClient2.default.convertToType(data['errors'], [_BasicError2.default]);
        }
      }
      return obj;
    }
  }]);

  return IndexJob;
}();

/**
 * The Job ID
 * @member {String} jobId
 */


IndexJob.prototype['jobId'] = undefined;

/**
 * The Model Set ID associated with the Job
 * @member {String} modelSetId
 */
IndexJob.prototype['modelSetId'] = undefined;

/**
 * The version associated with the Job
 * @member {Number} modelSetVersion
 */
IndexJob.prototype['modelSetVersion'] = undefined;

/**
 * @member {module:model/IndexQueryResources} resources
 */
IndexJob.prototype['resources'] = undefined;

/**
 * The current Job status
 * @member {module:model/IndexJob.StatusEnum} status
 */
IndexJob.prototype['status'] = undefined;

/**
 * @member {module:model/Job} job
 */
IndexJob.prototype['job'] = undefined;

/**
 * @member {Array.<module:model/BasicError>} errors
 */
IndexJob.prototype['errors'] = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
IndexJob['StatusEnum'] = {

  /**
   * value: "Failed"
   * @const
   */
  "Failed": "Failed",

  /**
   * value: "Running"
   * @const
   */
  "Running": "Running",

  /**
   * value: "Succeeded"
   * @const
   */
  "Succeeded": "Succeeded",

  /**
   * value: "Archived"
   * @const
   */
  "Archived": "Archived"
};

exports.default = IndexJob;
//# sourceMappingURL=IndexJob.js.map