'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Clash Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 3.3.12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The ClashTestSummary model module.
 * @module model/ClashTestSummary
 * @version 3.3.12
 */
var ClashTestSummary = function () {
  /**
   * Constructs a new <code>ClashTestSummary</code>.
   * @alias module:model/ClashTestSummary
   * @param id {String} 
   * @param modelSetId {String} 
   * @param modelSetVersion {Number} 
   * @param status {module:model/ClashTestSummary.StatusEnum} 
   */
  function ClashTestSummary(id, modelSetId, modelSetVersion, status) {
    _classCallCheck(this, ClashTestSummary);

    ClashTestSummary.initialize(this, id, modelSetId, modelSetVersion, status);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(ClashTestSummary, null, [{
    key: 'initialize',
    value: function initialize(obj, id, modelSetId, modelSetVersion, status) {
      obj['id'] = id;
      obj['modelSetId'] = modelSetId;
      obj['modelSetVersion'] = modelSetVersion;
      obj['status'] = status;
    }

    /**
     * Constructs a <code>ClashTestSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClashTestSummary} obj Optional instance to populate.
     * @return {module:model/ClashTestSummary} The populated <code>ClashTestSummary</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new ClashTestSummary();

        if (data.hasOwnProperty('id')) {
          obj['id'] = _ApiClient2.default.convertToType(data['id'], 'String');
        }
        if (data.hasOwnProperty('completedOn')) {
          obj['completedOn'] = _ApiClient2.default.convertToType(data['completedOn'], 'Date');
        }
        if (data.hasOwnProperty('modelSetId')) {
          obj['modelSetId'] = _ApiClient2.default.convertToType(data['modelSetId'], 'String');
        }
        if (data.hasOwnProperty('modelSetVersion')) {
          obj['modelSetVersion'] = _ApiClient2.default.convertToType(data['modelSetVersion'], 'Number');
        }
        if (data.hasOwnProperty('status')) {
          obj['status'] = _ApiClient2.default.convertToType(data['status'], 'String');
        }
      }
      return obj;
    }
  }]);

  return ClashTestSummary;
}();

/**
 * @member {String} id
 */


ClashTestSummary.prototype['id'] = undefined;

/**
 * @member {Date} completedOn
 */
ClashTestSummary.prototype['completedOn'] = undefined;

/**
 * @member {String} modelSetId
 */
ClashTestSummary.prototype['modelSetId'] = undefined;

/**
 * @member {Number} modelSetVersion
 */
ClashTestSummary.prototype['modelSetVersion'] = undefined;

/**
 * @member {module:model/ClashTestSummary.StatusEnum} status
 */
ClashTestSummary.prototype['status'] = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
ClashTestSummary['StatusEnum'] = {

  /**
   * value: "Pending"
   * @const
   */
  "Pending": "Pending",

  /**
   * value: "Processing"
   * @const
   */
  "Processing": "Processing",

  /**
   * value: "Success"
   * @const
   */
  "Success": "Success",

  /**
   * value: "Failed"
   * @const
   */
  "Failed": "Failed"
};

exports.default = ClashTestSummary;
//# sourceMappingURL=ClashTestSummary.js.map