'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Clash Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 3.3.12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The ClashGroupClashDataClashes model module.
 * @module model/ClashGroupClashDataClashes
 * @version 3.3.12
 */
var ClashGroupClashDataClashes = function () {
  /**
   * Constructs a new <code>ClashGroupClashDataClashes</code>.
   * @alias module:model/ClashGroupClashDataClashes
   */
  function ClashGroupClashDataClashes() {
    _classCallCheck(this, ClashGroupClashDataClashes);

    ClashGroupClashDataClashes.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(ClashGroupClashDataClashes, null, [{
    key: 'initialize',
    value: function initialize(obj) {}

    /**
     * Constructs a <code>ClashGroupClashDataClashes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClashGroupClashDataClashes} obj Optional instance to populate.
     * @return {module:model/ClashGroupClashDataClashes} The populated <code>ClashGroupClashDataClashes</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new ClashGroupClashDataClashes();

        if (data.hasOwnProperty('id')) {
          obj['id'] = _ApiClient2.default.convertToType(data['id'], 'Number');
        }
        if (data.hasOwnProperty('clash')) {
          obj['clash'] = _ApiClient2.default.convertToType(data['clash'], ['Number']);
        }
        if (data.hasOwnProperty('dist')) {
          obj['dist'] = _ApiClient2.default.convertToType(data['dist'], 'Number');
        }
        if (data.hasOwnProperty('status')) {
          obj['status'] = _ApiClient2.default.convertToType(data['status'], 'String');
        }
      }
      return obj;
    }
  }]);

  return ClashGroupClashDataClashes;
}();

/**
 * The clash index ID
 * @member {Number} id
 */


ClashGroupClashDataClashes.prototype['id'] = undefined;

/**
 * The clash instance index ID
 * @member {Array.<Number>} clash
 */
ClashGroupClashDataClashes.prototype['clash'] = undefined;

/**
 * The clash distance
 * @member {Number} dist
 */
ClashGroupClashDataClashes.prototype['dist'] = undefined;

/**
 * The status of the clash
 * @member {String} status
 */
ClashGroupClashDataClashes.prototype['status'] = undefined;

exports.default = ClashGroupClashDataClashes;
//# sourceMappingURL=ClashGroupClashDataClashes.js.map