'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Clash Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 3.3.12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _ClashTestResource = require('./ClashTestResource');

var _ClashTestResource2 = _interopRequireDefault(_ClashTestResource);

var _CollectionPage = require('./CollectionPage');

var _CollectionPage2 = _interopRequireDefault(_CollectionPage);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The ClashTestResourceCollection model module.
 * @module model/ClashTestResourceCollection
 * @version 3.3.12
 */
var ClashTestResourceCollection = function () {
  /**
   * Constructs a new <code>ClashTestResourceCollection</code>.
   * A Clash Test Resource collection.
   * @alias module:model/ClashTestResourceCollection
   * @param page {module:model/CollectionPage} 
   * @param resources {Array.<module:model/ClashTestResource>} List of resources.
   */
  function ClashTestResourceCollection(page, resources) {
    _classCallCheck(this, ClashTestResourceCollection);

    ClashTestResourceCollection.initialize(this, page, resources);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(ClashTestResourceCollection, null, [{
    key: 'initialize',
    value: function initialize(obj, page, resources) {
      obj['page'] = page;
      obj['resources'] = resources;
    }

    /**
     * Constructs a <code>ClashTestResourceCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClashTestResourceCollection} obj Optional instance to populate.
     * @return {module:model/ClashTestResourceCollection} The populated <code>ClashTestResourceCollection</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new ClashTestResourceCollection();

        if (data.hasOwnProperty('page')) {
          obj['page'] = _CollectionPage2.default.constructFromObject(data['page']);
        }
        if (data.hasOwnProperty('resources')) {
          obj['resources'] = _ApiClient2.default.convertToType(data['resources'], [_ClashTestResource2.default]);
        }
      }
      return obj;
    }
  }]);

  return ClashTestResourceCollection;
}();

/**
 * @member {module:model/CollectionPage} page
 */


ClashTestResourceCollection.prototype['page'] = undefined;

/**
 * List of resources.
 * @member {Array.<module:model/ClashTestResource>} resources
 */
ClashTestResourceCollection.prototype['resources'] = undefined;

exports.default = ClashTestResourceCollection;
//# sourceMappingURL=ClashTestResourceCollection.js.map