'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Clash Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 3.3.12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _ClashTestSummary = require('./ClashTestSummary');

var _ClashTestSummary2 = _interopRequireDefault(_ClashTestSummary);

var _CollectionPage = require('./CollectionPage');

var _CollectionPage2 = _interopRequireDefault(_CollectionPage);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The ClashTestSummaryCollection model module.
 * @module model/ClashTestSummaryCollection
 * @version 3.3.12
 */
var ClashTestSummaryCollection = function () {
  /**
   * Constructs a new <code>ClashTestSummaryCollection</code>.
   * A Clash Test Summary collection.
   * @alias module:model/ClashTestSummaryCollection
   * @param page {module:model/CollectionPage} 
   * @param tests {Array.<module:model/ClashTestSummary>} List of tests.
   */
  function ClashTestSummaryCollection(page, tests) {
    _classCallCheck(this, ClashTestSummaryCollection);

    ClashTestSummaryCollection.initialize(this, page, tests);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(ClashTestSummaryCollection, null, [{
    key: 'initialize',
    value: function initialize(obj, page, tests) {
      obj['page'] = page;
      obj['tests'] = tests;
    }

    /**
     * Constructs a <code>ClashTestSummaryCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClashTestSummaryCollection} obj Optional instance to populate.
     * @return {module:model/ClashTestSummaryCollection} The populated <code>ClashTestSummaryCollection</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new ClashTestSummaryCollection();

        if (data.hasOwnProperty('page')) {
          obj['page'] = _CollectionPage2.default.constructFromObject(data['page']);
        }
        if (data.hasOwnProperty('tests')) {
          obj['tests'] = _ApiClient2.default.convertToType(data['tests'], [_ClashTestSummary2.default]);
        }
      }
      return obj;
    }
  }]);

  return ClashTestSummaryCollection;
}();

/**
 * @member {module:model/CollectionPage} page
 */


ClashTestSummaryCollection.prototype['page'] = undefined;

/**
 * List of tests.
 * @member {Array.<module:model/ClashTestSummary>} tests
 */
ClashTestSummaryCollection.prototype['tests'] = undefined;

exports.default = ClashTestSummaryCollection;
//# sourceMappingURL=ClashTestSummaryCollection.js.map