'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Clash Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 3.3.12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The ClashGroupClashDataDocuments model module.
 * @module model/ClashGroupClashDataDocuments
 * @version 3.3.12
 */
var ClashGroupClashDataDocuments = function () {
  /**
   * Constructs a new <code>ClashGroupClashDataDocuments</code>.
   * @alias module:model/ClashGroupClashDataDocuments
   */
  function ClashGroupClashDataDocuments() {
    _classCallCheck(this, ClashGroupClashDataDocuments);

    ClashGroupClashDataDocuments.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(ClashGroupClashDataDocuments, null, [{
    key: 'initialize',
    value: function initialize(obj) {}

    /**
     * Constructs a <code>ClashGroupClashDataDocuments</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClashGroupClashDataDocuments} obj Optional instance to populate.
     * @return {module:model/ClashGroupClashDataDocuments} The populated <code>ClashGroupClashDataDocuments</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new ClashGroupClashDataDocuments();

        if (data.hasOwnProperty('id')) {
          obj['id'] = _ApiClient2.default.convertToType(data['id'], 'Number');
        }
        if (data.hasOwnProperty('urn')) {
          obj['urn'] = _ApiClient2.default.convertToType(data['urn'], 'String');
        }
      }
      return obj;
    }
  }]);

  return ClashGroupClashDataDocuments;
}();

/**
 * The document index ID
 * @member {Number} id
 */


ClashGroupClashDataDocuments.prototype['id'] = undefined;

/**
 * The document URN
 * @member {String} urn
 */
ClashGroupClashDataDocuments.prototype['urn'] = undefined;

exports.default = ClashGroupClashDataDocuments;
//# sourceMappingURL=ClashGroupClashDataDocuments.js.map