'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Clash Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 3.3.12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The ClashGroupClashDataClashInstances model module.
 * @module model/ClashGroupClashDataClashInstances
 * @version 3.3.12
 */
var ClashGroupClashDataClashInstances = function () {
  /**
   * Constructs a new <code>ClashGroupClashDataClashInstances</code>.
   * @alias module:model/ClashGroupClashDataClashInstances
   */
  function ClashGroupClashDataClashInstances() {
    _classCallCheck(this, ClashGroupClashDataClashInstances);

    ClashGroupClashDataClashInstances.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(ClashGroupClashDataClashInstances, null, [{
    key: 'initialize',
    value: function initialize(obj) {}

    /**
     * Constructs a <code>ClashGroupClashDataClashInstances</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClashGroupClashDataClashInstances} obj Optional instance to populate.
     * @return {module:model/ClashGroupClashDataClashInstances} The populated <code>ClashGroupClashDataClashInstances</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new ClashGroupClashDataClashInstances();

        if (data.hasOwnProperty('cid')) {
          obj['cid'] = _ApiClient2.default.convertToType(data['cid'], 'Number');
        }
        if (data.hasOwnProperty('ldid')) {
          obj['ldid'] = _ApiClient2.default.convertToType(data['ldid'], 'Number');
        }
        if (data.hasOwnProperty('loid')) {
          obj['loid'] = _ApiClient2.default.convertToType(data['loid'], 'Number');
        }
        if (data.hasOwnProperty('lvid')) {
          obj['lvid'] = _ApiClient2.default.convertToType(data['lvid'], 'Number');
        }
        if (data.hasOwnProperty('rdid')) {
          obj['rdid'] = _ApiClient2.default.convertToType(data['rdid'], 'Number');
        }
        if (data.hasOwnProperty('roid')) {
          obj['roid'] = _ApiClient2.default.convertToType(data['roid'], 'Number');
        }
        if (data.hasOwnProperty('rvid')) {
          obj['rvid'] = _ApiClient2.default.convertToType(data['rvid'], 'Number');
        }
      }
      return obj;
    }
  }]);

  return ClashGroupClashDataClashInstances;
}();

/**
 * The clash ID in the model set version
 * @member {Number} cid
 */


ClashGroupClashDataClashInstances.prototype['cid'] = undefined;

/**
 * The left-hand-side document ID
 * @member {Number} ldid
 */
ClashGroupClashDataClashInstances.prototype['ldid'] = undefined;

/**
 * The left-hand-side object ID
 * @member {Number} loid
 */
ClashGroupClashDataClashInstances.prototype['loid'] = undefined;

/**
 * The left-hand-side viewable ID
 * @member {Number} lvid
 */
ClashGroupClashDataClashInstances.prototype['lvid'] = undefined;

/**
 * The right-hand-side document ID
 * @member {Number} rdid
 */
ClashGroupClashDataClashInstances.prototype['rdid'] = undefined;

/**
 * The right-hand-side object ID
 * @member {Number} roid
 */
ClashGroupClashDataClashInstances.prototype['roid'] = undefined;

/**
 * The left-hand-side viewable ID
 * @member {Number} rvid
 */
ClashGroupClashDataClashInstances.prototype['rvid'] = undefined;

exports.default = ClashGroupClashDataClashInstances;
//# sourceMappingURL=ClashGroupClashDataClashInstances.js.map