'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Clash Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 3.3.12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _Job = require('./Job');

var _Job2 = _interopRequireDefault(_Job);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The ClashGroupJob model module.
 * @module model/ClashGroupJob
 * @version 3.3.12
 */
var ClashGroupJob = function () {
  /**
   * Constructs a new <code>ClashGroupJob</code>.
   * Clash Group Job
   * @alias module:model/ClashGroupJob
   * @param jobId {String} Job ID
   * @param groups {Array.<String>} Clash Group ID
   * @param status {module:model/ClashGroupJob.StatusEnum} Job status
   * @param job {module:model/Job} 
   */
  function ClashGroupJob(jobId, groups, status, job) {
    _classCallCheck(this, ClashGroupJob);

    ClashGroupJob.initialize(this, jobId, groups, status, job);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(ClashGroupJob, null, [{
    key: 'initialize',
    value: function initialize(obj, jobId, groups, status, job) {
      obj['jobId'] = jobId;
      obj['groups'] = groups;
      obj['status'] = status;
      obj['job'] = job;
    }

    /**
     * Constructs a <code>ClashGroupJob</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClashGroupJob} obj Optional instance to populate.
     * @return {module:model/ClashGroupJob} The populated <code>ClashGroupJob</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new ClashGroupJob();

        if (data.hasOwnProperty('jobId')) {
          obj['jobId'] = _ApiClient2.default.convertToType(data['jobId'], 'String');
        }
        if (data.hasOwnProperty('groups')) {
          obj['groups'] = _ApiClient2.default.convertToType(data['groups'], ['String']);
        }
        if (data.hasOwnProperty('status')) {
          obj['status'] = _ApiClient2.default.convertToType(data['status'], 'String');
        }
        if (data.hasOwnProperty('job')) {
          obj['job'] = _Job2.default.constructFromObject(data['job']);
        }
      }
      return obj;
    }
  }]);

  return ClashGroupJob;
}();

/**
 * Job ID
 * @member {String} jobId
 */


ClashGroupJob.prototype['jobId'] = undefined;

/**
 * Clash Group ID
 * @member {Array.<String>} groups
 */
ClashGroupJob.prototype['groups'] = undefined;

/**
 * Job status
 * @member {module:model/ClashGroupJob.StatusEnum} status
 */
ClashGroupJob.prototype['status'] = undefined;

/**
 * @member {module:model/Job} job
 */
ClashGroupJob.prototype['job'] = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
ClashGroupJob['StatusEnum'] = {

  /**
   * value: "Failed"
   * @const
   */
  "Failed": "Failed",

  /**
   * value: "Running"
   * @const
   */
  "Running": "Running",

  /**
   * value: "Succeeded"
   * @const
   */
  "Succeeded": "Succeeded",

  /**
   * value: "Archived"
   * @const
   */
  "Archived": "Archived"
};

exports.default = ClashGroupJob;
//# sourceMappingURL=ClashGroupJob.js.map