"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Clash Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 3.3.12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require("../ApiClient");

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* Enum class CloseReason.
* @enum {}
* @readonly
*/
var CloseReason = function () {
    function CloseReason() {
        _classCallCheck(this, CloseReason);

        this["OTHER"] = "OTHER";
        this["VALID_INTERFACE"] = "VALID_INTERFACE";
        this["VALID_PENETRATION"] = "VALID_PENETRATION";
        this["MINIMAL_OVERLAP"] = "MINIMAL_OVERLAP";
        this["ITEM_CAN_FLEX"] = "ITEM_CAN_FLEX";
        this["MODEL_INACCURACY"] = "MODEL_INACCURACY";
        this["FIELD_FIX"] = "FIELD_FIX";
    }

    /**
     * value: "OTHER"
     * @const
     */


    /**
     * value: "VALID_INTERFACE"
     * @const
     */


    /**
     * value: "VALID_PENETRATION"
     * @const
     */


    /**
     * value: "MINIMAL_OVERLAP"
     * @const
     */


    /**
     * value: "ITEM_CAN_FLEX"
     * @const
     */


    /**
     * value: "MODEL_INACCURACY"
     * @const
     */


    /**
     * value: "FIELD_FIX"
     * @const
     */


    _createClass(CloseReason, null, [{
        key: "constructFromObject",


        /**
        * Returns a <code>CloseReason</code> enum value from a Javascript object name.
        * @param {Object} data The plain JavaScript object containing the name of the enum value.
        * @return {module:model/CloseReason} The enum <code>CloseReason</code> value.
        */
        value: function constructFromObject(object) {
            return object;
        }
    }]);

    return CloseReason;
}();

exports.default = CloseReason;
//# sourceMappingURL=CloseReason.js.map