'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Clash Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 3.3.12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _ClashGroupClashData = require('./ClashGroupClashData');

var _ClashGroupClashData2 = _interopRequireDefault(_ClashGroupClashData);

var _CloseReason = require('./CloseReason');

var _CloseReason2 = _interopRequireDefault(_CloseReason);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The ClosedClashGroupClashData model module.
 * @module model/ClosedClashGroupClashData
 * @version 3.3.12
 */
var ClosedClashGroupClashData = function () {
  /**
   * Constructs a new <code>ClosedClashGroupClashData</code>.
   * A Closed Clash Group
   * @alias module:model/ClosedClashGroupClashData
   * @param clashTestId {String} 
   * @param title {String} 
   * @param reason {module:model/CloseReason} 
   */
  function ClosedClashGroupClashData(clashTestId, title, reason) {
    _classCallCheck(this, ClosedClashGroupClashData);

    ClosedClashGroupClashData.initialize(this, clashTestId, title, reason);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(ClosedClashGroupClashData, null, [{
    key: 'initialize',
    value: function initialize(obj, clashTestId, title, reason) {
      obj['clashTestId'] = clashTestId;
      obj['title'] = title;
      obj['reason'] = reason;
    }

    /**
     * Constructs a <code>ClosedClashGroupClashData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClosedClashGroupClashData} obj Optional instance to populate.
     * @return {module:model/ClosedClashGroupClashData} The populated <code>ClosedClashGroupClashData</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new ClosedClashGroupClashData();

        if (data.hasOwnProperty('id')) {
          obj['id'] = _ApiClient2.default.convertToType(data['id'], 'String');
        }
        if (data.hasOwnProperty('clashTestId')) {
          obj['clashTestId'] = _ApiClient2.default.convertToType(data['clashTestId'], 'String');
        }
        if (data.hasOwnProperty('title')) {
          obj['title'] = _ApiClient2.default.convertToType(data['title'], 'String');
        }
        if (data.hasOwnProperty('description')) {
          obj['description'] = _ApiClient2.default.convertToType(data['description'], 'String');
        }
        if (data.hasOwnProperty('reason')) {
          obj['reason'] = _CloseReason2.default.constructFromObject(data['reason']);
        }
        if (data.hasOwnProperty('screenShots')) {
          obj['screenShots'] = _ApiClient2.default.convertToType(data['screenShots'], ['String']);
        }
        if (data.hasOwnProperty('createdBy')) {
          obj['createdBy'] = _ApiClient2.default.convertToType(data['createdBy'], 'String');
        }
        if (data.hasOwnProperty('createdOn')) {
          obj['createdOn'] = _ApiClient2.default.convertToType(data['createdOn'], 'Date');
        }
        if (data.hasOwnProperty('clashData')) {
          obj['clashData'] = _ClashGroupClashData2.default.constructFromObject(data['clashData']);
        }
      }
      return obj;
    }
  }]);

  return ClosedClashGroupClashData;
}();

/**
 * @member {String} id
 */


ClosedClashGroupClashData.prototype['id'] = undefined;

/**
 * @member {String} clashTestId
 */
ClosedClashGroupClashData.prototype['clashTestId'] = undefined;

/**
 * @member {String} title
 */
ClosedClashGroupClashData.prototype['title'] = undefined;

/**
 * @member {String} description
 */
ClosedClashGroupClashData.prototype['description'] = undefined;

/**
 * @member {module:model/CloseReason} reason
 */
ClosedClashGroupClashData.prototype['reason'] = undefined;

/**
 * @member {Array.<String>} screenShots
 */
ClosedClashGroupClashData.prototype['screenShots'] = undefined;

/**
 * @member {String} createdBy
 */
ClosedClashGroupClashData.prototype['createdBy'] = undefined;

/**
 * @member {Date} createdOn
 */
ClosedClashGroupClashData.prototype['createdOn'] = undefined;

/**
 * @member {module:model/ClashGroupClashData} clashData
 */
ClosedClashGroupClashData.prototype['clashData'] = undefined;

exports.default = ClosedClashGroupClashData;
//# sourceMappingURL=ClosedClashGroupClashData.js.map