'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Clash Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 3.3.12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _CustomAttribute = require('./CustomAttribute');

var _CustomAttribute2 = _interopRequireDefault(_CustomAttribute);

var _Pushpin = require('./Pushpin');

var _Pushpin2 = _interopRequireDefault(_Pushpin);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The NewAssignedClashGroup model module.
 * @module model/NewAssignedClashGroup
 * @version 3.3.12
 */
var NewAssignedClashGroup = function () {
  /**
   * Constructs a new <code>NewAssignedClashGroup</code>.
   * A Clash Group
   * @alias module:model/NewAssignedClashGroup
   * @param title {String} 
   * @param documentLineageUrn {String} 
   * @param documentVersion {Number} 
   * @param assignedTo {String} 
   * @param pushpin {module:model/Pushpin} 
   * @param clashes {Array.<Number>} 
   */
  function NewAssignedClashGroup(title, documentLineageUrn, documentVersion, assignedTo, pushpin, clashes) {
    _classCallCheck(this, NewAssignedClashGroup);

    NewAssignedClashGroup.initialize(this, title, documentLineageUrn, documentVersion, assignedTo, pushpin, clashes);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(NewAssignedClashGroup, null, [{
    key: 'initialize',
    value: function initialize(obj, title, documentLineageUrn, documentVersion, assignedTo, pushpin, clashes) {
      obj['title'] = title;
      obj['documentLineageUrn'] = documentLineageUrn;
      obj['documentVersion'] = documentVersion;
      obj['assignedTo'] = assignedTo;
      obj['pushpin'] = pushpin;
      obj['clashes'] = clashes;
    }

    /**
     * Constructs a <code>NewAssignedClashGroup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewAssignedClashGroup} obj Optional instance to populate.
     * @return {module:model/NewAssignedClashGroup} The populated <code>NewAssignedClashGroup</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new NewAssignedClashGroup();

        if (data.hasOwnProperty('id')) {
          obj['id'] = _ApiClient2.default.convertToType(data['id'], 'String');
        }
        if (data.hasOwnProperty('title')) {
          obj['title'] = _ApiClient2.default.convertToType(data['title'], 'String');
        }
        if (data.hasOwnProperty('description')) {
          obj['description'] = _ApiClient2.default.convertToType(data['description'], 'String');
        }
        if (data.hasOwnProperty('documentLineageUrn')) {
          obj['documentLineageUrn'] = _ApiClient2.default.convertToType(data['documentLineageUrn'], 'String');
        }
        if (data.hasOwnProperty('documentVersion')) {
          obj['documentVersion'] = _ApiClient2.default.convertToType(data['documentVersion'], 'Number');
        }
        if (data.hasOwnProperty('assignedTo')) {
          obj['assignedTo'] = _ApiClient2.default.convertToType(data['assignedTo'], 'String');
        }
        if (data.hasOwnProperty('assignedToType')) {
          obj['assignedToType'] = _ApiClient2.default.convertToType(data['assignedToType'], 'String');
        }
        if (data.hasOwnProperty('dueDate')) {
          obj['dueDate'] = _ApiClient2.default.convertToType(data['dueDate'], 'Date');
        }
        if (data.hasOwnProperty('pushpin')) {
          obj['pushpin'] = _Pushpin2.default.constructFromObject(data['pushpin']);
        }
        if (data.hasOwnProperty('clashes')) {
          obj['clashes'] = _ApiClient2.default.convertToType(data['clashes'], ['Number']);
        }
        if (data.hasOwnProperty('issueTypeId')) {
          obj['issueTypeId'] = _ApiClient2.default.convertToType(data['issueTypeId'], 'String');
        }
        if (data.hasOwnProperty('issueSubTypeId')) {
          obj['issueSubTypeId'] = _ApiClient2.default.convertToType(data['issueSubTypeId'], 'String');
        }
        if (data.hasOwnProperty('rootCauseId')) {
          obj['rootCauseId'] = _ApiClient2.default.convertToType(data['rootCauseId'], 'String');
        }
        if (data.hasOwnProperty('customAttributes')) {
          obj['customAttributes'] = _ApiClient2.default.convertToType(data['customAttributes'], [_CustomAttribute2.default]);
        }
        if (data.hasOwnProperty('screenShots')) {
          obj['screenShots'] = _ApiClient2.default.convertToType(data['screenShots'], ['String']);
        }
      }
      return obj;
    }
  }]);

  return NewAssignedClashGroup;
}();

/**
 * @member {String} id
 */


NewAssignedClashGroup.prototype['id'] = undefined;

/**
 * @member {String} title
 */
NewAssignedClashGroup.prototype['title'] = undefined;

/**
 * @member {String} description
 */
NewAssignedClashGroup.prototype['description'] = undefined;

/**
 * @member {String} documentLineageUrn
 */
NewAssignedClashGroup.prototype['documentLineageUrn'] = undefined;

/**
 * @member {Number} documentVersion
 */
NewAssignedClashGroup.prototype['documentVersion'] = undefined;

/**
 * @member {String} assignedTo
 */
NewAssignedClashGroup.prototype['assignedTo'] = undefined;

/**
 * @member {module:model/NewAssignedClashGroup.AssignedToTypeEnum} assignedToType
 * @default 'User'
 */
NewAssignedClashGroup.prototype['assignedToType'] = 'User';

/**
 * @member {Date} dueDate
 */
NewAssignedClashGroup.prototype['dueDate'] = undefined;

/**
 * @member {module:model/Pushpin} pushpin
 */
NewAssignedClashGroup.prototype['pushpin'] = undefined;

/**
 * @member {Array.<Number>} clashes
 */
NewAssignedClashGroup.prototype['clashes'] = undefined;

/**
 * @member {String} issueTypeId
 */
NewAssignedClashGroup.prototype['issueTypeId'] = undefined;

/**
 * @member {String} issueSubTypeId
 */
NewAssignedClashGroup.prototype['issueSubTypeId'] = undefined;

/**
 * @member {String} rootCauseId
 */
NewAssignedClashGroup.prototype['rootCauseId'] = undefined;

/**
 * @member {Array.<module:model/CustomAttribute>} customAttributes
 */
NewAssignedClashGroup.prototype['customAttributes'] = undefined;

/**
 * @member {Array.<String>} screenShots
 */
NewAssignedClashGroup.prototype['screenShots'] = undefined;

/**
 * Allowed values for the <code>assignedToType</code> property.
 * @enum {String}
 * @readonly
 */
NewAssignedClashGroup['AssignedToTypeEnum'] = {

  /**
   * value: "User"
   * @const
   */
  "User": "User",

  /**
   * value: "Role"
   * @const
   */
  "Role": "Role",

  /**
   * value: "Company"
   * @const
   */
  "Company": "Company"
};

exports.default = NewAssignedClashGroup;
//# sourceMappingURL=NewAssignedClashGroup.js.map