'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Clash Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 3.3.12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The PushpinLocation model module.
 * @module model/PushpinLocation
 * @version 3.3.12
 */
var PushpinLocation = function () {
  /**
   * Constructs a new <code>PushpinLocation</code>.
   * @alias module:model/PushpinLocation
   * @param x {Number} 
   * @param y {Number} 
   * @param z {Number} 
   */
  function PushpinLocation(x, y, z) {
    _classCallCheck(this, PushpinLocation);

    PushpinLocation.initialize(this, x, y, z);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(PushpinLocation, null, [{
    key: 'initialize',
    value: function initialize(obj, x, y, z) {
      obj['x'] = x;
      obj['y'] = y;
      obj['z'] = z;
    }

    /**
     * Constructs a <code>PushpinLocation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PushpinLocation} obj Optional instance to populate.
     * @return {module:model/PushpinLocation} The populated <code>PushpinLocation</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new PushpinLocation();

        if (data.hasOwnProperty('x')) {
          obj['x'] = _ApiClient2.default.convertToType(data['x'], 'Number');
        }
        if (data.hasOwnProperty('y')) {
          obj['y'] = _ApiClient2.default.convertToType(data['y'], 'Number');
        }
        if (data.hasOwnProperty('z')) {
          obj['z'] = _ApiClient2.default.convertToType(data['z'], 'Number');
        }
      }
      return obj;
    }
  }]);

  return PushpinLocation;
}();

/**
 * @member {Number} x
 */


PushpinLocation.prototype['x'] = undefined;

/**
 * @member {Number} y
 */
PushpinLocation.prototype['y'] = undefined;

/**
 * @member {Number} z
 */
PushpinLocation.prototype['z'] = undefined;

exports.default = PushpinLocation;
//# sourceMappingURL=PushpinLocation.js.map